server:
  port: 8081
spring:
  application:
    name: moviedp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dydp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.88.128
    username: zkk
    password: 123456
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true                 # 启用重试
          max-attempts: 3               # 最大重试次数
          initial-interval: 1000ms      # 初始重试间隔
          multiplier: 2                 # 间隔倍数
          max-interval: 10000ms         # 最大间隔
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
mybatis-plus:
  type-aliases-package: com.zkk.moviedp.entity # 别名扫描包
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-9f9c1fe594df4e38af4e524caa447a6b
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
#  community:
#    dashscope:
#      chat-model:
#        api-key: sk-394bfe08c2914c68af83262734cd4ff9
#        model-name: qwen-max
logging:
  level:
    com.zkk.moviedp: debug
